# Generated by Django 4.2.3 on 2023-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
